### ISSUE TITLE
primevideo.com not working correctly

### ISSUE THREAD

**Issue by Notlucky101** [Dreamlinerm/Netflix-Prime-Auto-Skip#106]
Looks like prime video found a way to stop the app from working. Please look  into it. Thanks

**Comment by Dreamlinerm** [comment]
what is not working excatly? in which country? this is why i set up issue templates

**Comment by Dreamlinerm** [comment]
for me everything seems to be working fine

**Comment by Notlucky101** [comment]
sorry about that I Live in Canada, Surrey, British Columbia.

**Comment by Dreamlinerm** [comment]
> sorry about that I Live in Canada, Surrey, British Columbia.

So which feature is not working correctly the ad blocking?

**Comment by Gachimuchi4ever** [comment]
sorry in advance for my writing... meaby is the same problem, I had the error a few times, I discovered that it only happens when there is a string AFTER "/ref=atv_dp_season_select_s?", this string appears sometimes when you search for specific episodes by scrolling through the seasons of a TV series.
By deleting the string, you return to the selection of episodes, and when you select the episode again, everything goes back to working properly, skipping the advertisements, because the string is no longer used to play the episode.
I'm in ITALY

SOMETIMES NOT WORKING:
https://www.primevideo.com/detail/0QSSYC71J84KFLUONLGVGFBVV5/ref=atv_dp_season_select_s5?jic=8%7CEgNhbGw%3D

WORKING:
https://www.primevideo.com/detail/0QSSYC71J84KFLUONLGVGFBVV5/ref=atv_dp_season_select_s5

**Comment by Dreamlinerm** [comment]
> sorry in advance for my writing... meaby is the same problem, I had the error a few times, I discovered that it only happens when there is a string AFTER "/ref=atv_dp_season_select_s?", this string appears sometimes when you search for specific episodes by scrolling through the seasons of a TV series. By deleting the string, you return to the selection of episodes, and when you select the episode again, everything goes back to working properly, skipping the advertisements, because the string is no longer used to play the episode. I'm in ITALY
> 
> SOMETIMES NOT WORKING: https://www.primevideo.com/detail/0QSSYC71J84KFLUONLGVGFBVV5/ref=atv_dp_season_select_s5?jic=8%7CEgNhbGw%3D
> 
> WORKING: https://www.primevideo.com/detail/0QSSYC71J84KFLUONLGVGFBVV5/ref=atv_dp_season_select_s5

i think it is the same problem, because i think only primevideo.com is affected. let me use a vpn to got to italy. i will look into it tomorrow, why the different urls make a difference

**Comment by Dreamlinerm** [comment]
@Gachimuchi4ever  Even with VPN I cannot watch a video on primevideo.com because they know my account is from Germany, would you be able to come onto the discord server and show me the problem personally, that would be of great help https://discord.gg/aeXeHhAw . or if this is not possible, make a snapshot with the single file browser extension when the problem occurs.

**Comment by argetlam87** [comment]
I'm not sure if it's the same problem, but i'm from italy too, and when i try to watch a show on prime video i can no longer speed up the show. The control button disappeared from the interface even if it's enabled and works fine on disney and other platforms.

**Comment by Dreamlinerm** [comment]
> I'm not sure if it's the same problem, but i'm from italy too, and when i try to watch a show on prime video i can no longer speed up the show. The control button disappeared from the interface even if it's enabled and works fine on disney and other platforms.

I think they changed the website on primevideo.com a little can you send me a snapshot of every page that is not working correctly (with the single file extension), like the home page and the video player? or maybe show me the issue directly over discord? https://discord.gg/5fBYathA7d

**Comment by argetlam87** [comment]
I'm sorry, I tried, but I don't know how to use discord lol
Anyway, for example, i'm watching city hunter
Here is the url of the show
https://www.primevideo.com/detail/0HFHWAO4NYQMAWP8WDLW6HT0K3/ref=atv_hm_hom_c_cjm7wb_6_1?jic=8%7CEgNhbGw%3D
and here the player
![image](https://github.com/user-attachments/assets/72a03ff1-b5f1-4942-978b-7b4c0e09939b)

It changed by few days beacuse before i could change the speed and it's the same for every show.
I don't know if tha ads blocker works for prime, because i think ublock origin already block them on its own, i never had ads

**Comment by Dreamlinerm** [comment]
> I'm sorry, I tried, but I don't know how to use discord lol Anyway, for example, i'm watching city hunter Here is the url of the show https://www.primevideo.com/detail/0HFHWAO4NYQMAWP8WDLW6HT0K3/ref=atv_hm_hom_c_cjm7wb_6_1?jic=8%7CEgNhbGw%3D and here the player ![image](https://private-user-images.githubusercontent.com/176053394/350461081-72a03ff1-b5f1-4942-978b-7b4c0e09939b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0MDU1MTMsIm5iZiI6MTcyMTQwNTIxMywicGF0aCI6Ii8xNzYwNTMzOTQvMzUwNDYxMDgxLTcyYTAzZmYxLWI1ZjEtNDk0Mi05NzhiLTdiNGMwZTA5OTM5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOVQxNjA2NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMDJlYWQ1NTE3ZTY4YTFkOWEzZGY2NTgzYzZiNDYzMGY0ZTBiMDdmMThiYjczNWU4NjA2MDQ4NWY5ZDVmNzQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gukq3AzfyrLj1nhN3FdN_jKCQ-TY2ZqmSk-u57O9FuM)
> 
> It changed by few days beacuse before i could change the speed and it's the same for every show. I don't know if tha ads blocker works for prime, because i think ublock origin already block them on its own, i never had ads

Yeah, I cannot use primevideo.com because the domain is not available in my country, and I cannot fix the problem from a screenshot. Can you save the page with the SingleFile browser extension and send it over GitHub or discord?

**Comment by Dreamlinerm** [comment]
https://addons.mozilla.org/en-US/firefox/addon/single-file/
https://chromewebstore.google.com/detail/singlefile/mpiodijhokgodhhofbcjdecpffjipkle?hl=en

**Comment by Dreamlinerm** [comment]
NVM the website changed in my country now too i will fix now
